project:
  type: website
  output-dir: docs

website:
  title: "Desarrollo de paquetes de R útiles en ecología"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/EcologyR/workshop
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: funcionamiento.qmd
      - href: materials.qmd
        text: Materials
      - href: participantes.qmd
      - href: codigo-de-conducta.qmd
        text: Código de conducta
      - href: https://github.com/EcologyR/workshop/discussions
        text: Foro

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

