project:
  type: website
  output-dir: docs

website:
  title: "Desarrollo de paquetes de R útiles en ecología"
  sidebar:
    background: primary
    logo: "images/logoEcologyR.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/EcologyR/workshop
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: participantes.qmd
        text: Participantes
      - href: paquetes.qmd
        text: Paquetes
      - href: programa.qmd
      - href: funcionamiento.qmd
        text: Funcionamiento
      - href: codigo-de-conducta.qmd
        text: Código de conducta
      - href: recursos.qmd
      - href: https://github.com/EcologyR/workshop/discussions
        text: Foro


format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

