---
title: "Código de conducta"
---

La celebración de este taller pretende aglutinar una comunidad abierta, formada por miembros con un conjunto diverso de habilidades, personalidades y experiencias. Todos los miembros de la comunidad están obligados a seguir este código de conducta, para que la participación en la comunidad sea positiva, segura, inclusiva y exitosa para todos. En términos generales, la participación en esta comunidad debe ser

- Respetuosa: Respetamos a los demás, sus opiniones, sus habilidades, sus compromisos y sus esfuerzos. Respetamos los procesos establecidos en la comunidad y trabajamos dentro de ellos. Cuando no estamos de acuerdo, somos educados y respetuosos al plantear nuestros problemas.

- Abierta: los miembros de la comunidad están abiertos a la colaboración. Somos receptivos a los comentarios y críticas constructivas. Fomentamos un entorno en el que todos puedan participar. 

- No toleramos el acoso en ninguna forma, incluyendo:

  - Comentarios ofensivos relacionados con género, identidad y expresión de género, edad, orientación sexual, discapacidad, apariencia física, tamaño corporal, raza, origen étnico, religión (o falta de ellos), o preferencias tecnológicas
  - Comentarios no deseados con respecto al estilo de vida de una persona, incluidos los relacionados con la alimentación, la salud, la crianza de los hijos, las drogas o el empleo
  - Interrupción sostenida o voluntaria de discusiones, charlas u otros eventos.
  - Intimidación deliberada
  - Insistencia en la comunicación personal después de las solicitudes de cese.
  - Fotografía o grabación no deseada
  - Contacto social inapropiado, como solicitar/asumir niveles inapropiados de intimidad con otros
  - Contacto físico inapropiado sin consentimiento
  - Amenazas de violencia o incitación a la violencia contra cualquier persona
  - Uso de imágenes, comentarios o chistes sexuales o discriminatorios
  - Publicación de información sobre cualquier aspecto de la identidad de una persona sin su consentimiento, excepto cuando sea necesario para proteger a las personas vulnerables
  - Publicación de comunicación privada, excepto cuando sea necesario para proteger a las personas vulnerables
  
Si algún miembro no respeta este código de conducta, puede conllevar la expulsión del taller de forma temporal o permanente. Para comunicar cualquier incumplimiento o incidencia relacionada con este código de conducta, cualquier persona puede ponerse en contacto con Francisco Rodríguez Sánchez (f.rodriguez.sanc@gmail.com), Irene Mendoza (irene.mendoza.sagrera@gmail.com) o Ignasi Bartomeus (nacho.bartomeus@gmail.com), garantizándose la confidencialidad.

*Documento adaptado a partir del código de conducta de [ROpenSci](https://ropensci.org/codigo-de-conducta/)*


